### ISSUE TITLE
Validar al agregar un nuevo cliente que el NRC, NIT y DUI no exista otro repetido (validaciones independientes)

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-sale#23]

**Comment by alvarogarcia1010** [comment]
Listo!

**Comment by mgallegos** [comment]
2 Observaciones:
- En el código cambiar nombre de los métodos que se les puso NRC, NIT y DUI  por el nombres en ingles correspondiente a la columna en el sistema, por ejemplo $this->Client->countNIT debe ser $this->Client->countByTaxId.
- En caso que lo encuentré además del mensaje info, buscar agregar método de buscar cliente por la columna correspondiente(ejemplo: $this->Client->byTaxId y devolver en el json el id del cliente (tal y como se hace [cuando se agrega exitosament](https://github.com/mgallegos/decima-sale/blob/master/src/Mgallegos/DecimaSale/Sale/Services/ClientManagement/ClientManager.php#L433)e)

**Comment by mgallegos** [comment]
Antes de hacer los cambios anteriores, hacer pull para ver los cambios hecho ahí, revisa los cambios y luego te explico porque los hice.
