### ISSUE TITLE
Agregar campos de teléfono móvil y género (masculino o femenino), y cambiar teléfono por teléfono fijo

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-sale#57]
Script:
ALTER TABLE `SALE_Client` 
ADD COLUMN `mobile_phone_number` VARCHAR(60) NULL DEFAULT NULL AFTER `phone_number`,
ADD COLUMN `gender` CHAR(1) NULL DEFAULT NULL AFTER `frequent_number`;

ALTER TABLE `SALE_Client` 
ADD COLUMN `advertising_is_accepted` TINYINT(1) NULL DEFAULT '1' AFTER `gender`;

**Comment by alvarogarcia1010** [comment]
Listo!

**Comment by mgallegos** [comment]
Revisado.
