### ISSUE TITLE
En todas las pantallas con filtros, optimizar espacio de filtros para resoluciones de @media (min-width: 992px) and (max-width: 1199px) 

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-sale#62]

**Comment by alvarogarcia1010** [comment]
Pantallas Optimizadas:

- Gestion de ventas
- Gestion de afiliados
- Articulos Vendidos

Faltantes:

- Gestion de cuentas por cobrar
- Gestion de articulos
- Gestion de pagos recibidos
- Libro de ventas a contribuyentes
- Ventas a consumidor final
- Ventas realizadas
- Resumen de operaciones

**Comment by alvarogarcia1010** [comment]
**Listos:** 
- Gestión de Cuentas por cobrar
- Gestion de pagos recibidos
- Libro de ventas a contribuyentes
- Ventas a consumidor final
- Ventas realizadas
- Resumen de operaciones

**Comment by mgallegos** [comment]
Pasar @alvarogarcia1010 a Trello, y cerrar este issue:

 Falta:
- Antigüedad de saldos de cuentas por cobrar
