### ISSUE TITLE
Reporte de venta de artículos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-sale#64]
El grid debe tener las siguientes columnas:
- Las mismas de cuentas por cobrar pero agregar la columna de correlativo (sale_order_number)

Debe tener los siguientes filtros:
- Los mismo que cuentas por cobrar

Indicaciones:
- URL: /sales/reports/article-sales
- Nombre de la vista: article-sales.blade.php
- Utilizar el prefijo: sale-as-
- Utilizar todos los filtros ventas realizadas.
- Utilizar como base el reporte plantilla de reportes del sistema.
- Dentro de la carpeta Repositories/SaleOrder/EloquentArticleSalesGridRepository utilizar de base EloquentOrderDetailGridRepository
- Las mismas columnas que el "Detalle de artículos" de ventas, solo consolidar en un solo "Total", las 3 últimas columnas.
- Totalizar columna de cantidad y total.

**Comment by alvarogarcia1010** [comment]
Agregar al grid:
Correlativo de venta, numero de documento y tipo de documento

**Comment by alvarogarcia1010** [comment]
agregar marca, modelo, grupo y subgrupo

**Comment by mgallegos** [comment]
Realizar los siguientes ajustes:
- Agregar columna de fecha y cliente (después de correlat.)
- Esconder al inicio columna de nombre alternativo y observación
- Agregar checkbox de Mostrar nombre alternativo y Mostrar observación.
- Alinear a la izquierda columna de tipo de documento

**Comment by alvarogarcia1010** [comment]
Cambios realizados con exito!
