### ISSUE TITLE
Reporte de cuentas por cobrar a una fecha determinada

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-sale#72]
El grid debe tener las siguientes columnas:
- Las mismas del reporte de venta de artículos
- Cambiar la última por Monto a cobrar y agregar Monto cobrado

Debe tener los siguientes filtros:
- Rango de fecha de registro
- Cuenta contable (autocomplete, dejálo vacío por el momento)

Indicaciones:
- URL: /purchases/reports/given-date-receivable-accounts
- Nombre de la vista: given-date-receivable-accounts.blade.php
- Utilizar el prefijo: purch-gdpa-
- Utilizar como base el reporte de venta de artículos
- Controlador: GivenDateReceivableAccount
- Dentro de la carpeta Repositories/Order/EloquentGivenDateReceivableAccountGridRepository
- Totalizar columna de Monto a cobrar y Monto cobrado.

Pendiente el menú

**Comment by mgallegos** [comment]
Menú:

INSERT INTO `dev_decimaerp`.`SEC_Menu` (`name`, `lang_key`, `url`, `action_button_id`, `action_lang_key`, `icon`, `parent_id`, `created_by`, `module_id`) 
VALUES ('Given Date Receivable Accounts', 'decima-sale::menu.givenDateReceivableAccounts', '/sales/reports/article-sales', '', 'decima-sale::menu.givenDateReceivableAccountsAction', 'fa fa-file-text-o', '81', '1', '7');

**Comment by alvarogarcia1010** [comment]
Solo falta que funcione el filtro de cuenta contable, y la consulta del monto cobrado

**Comment by mgallegos** [comment]
Falta limpiar el controlador de todas las variables y servicios que no se están utilizando.
