### ISSUE TITLE
Crear pantalla de importación de ventas

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-sale#73]

**Comment by mgallegos** [comment]
@alvarogarcia1010: En la vista sale-import.blade.php favor de cambiar el id de los campos para que coincidan con el campo correspondiente en la base (tabla SALE_Order y SALE_Order_Detail) por ejemplo cambiar payment-term-column por payment-term-id-column  (siempre dejar el sufijo column).

**Comment by alvarogarcia1010** [comment]
@mgallegos: 
En el apartado de "Encabezado de documento" se corrigieron:
- [ ]  document-not-subject-column **(not-subject-amount-sum)**
- [ ]  document-exempt-column **(exempt-amount-sum)**
- [ ]  document-subject-column **(subject-amount-sum)**
- [ ]  document-tax-column **(collected-tax-amount-sum)**

En el apartado de "Detalle del documento":
- [ ] internal-reference-column **(undefine)**
- [ ] detail-remark-column **(se dejo tal cual)**
- [ ] not-subject-column **(not-subject-amount)**
- [ ] exempt-column **(exempt-amount)**
- [ ] subject-column **(subject-amount)**
